### ISSUE TITLE
Logout doesn't work all the time

### ISSUE THREAD

**Issue by ajkothari13** [RDCH106/Simple-File-Server#3]
1stly, many thanks for the great improvements.
...
I was able to logout on chrome (android). But firefox on ubuntu desktop did not logout even after repeated tries.

**Comment by RDCH106** [comment]
Hi @ajkothari13!

The problem is a detected bug in Firefox present since version 57. I reported it using twitter (in spanish):

https://twitter.com/RDCH106/status/931546346439442432

Also I reported it in official Firefox bug tracker (in english) 🐞:

https://bugzilla.mozilla.org/show_bug.cgi?id=1366222

Basically the problem concern to HTTP Basic Auth used to login because Firefox keeps cached the credentials despite the 401 code generated by logout. Firefox it is not respecting HTTP protocol. I think that it is a very problematic bug... Many applications like the webs to administrate the routers configration use HTTP Basic Auth to protect the access.

I can not solve it because it is not problem of my project... It is a bug in Firefox 🦊 as you can see!! 😉

**Comment by ajkothari13** [comment]
Oh, ok! Didn't know that. Good info.

Another thing, would you be interested in adding https support?

For example (a very simple one):
[Here](https://gist.github.com/dergachev/7028596)

**Comment by RDCH106** [comment]
It is good idea!!
But I don't have time right now... 😅

**Comment by ajkothari13** [comment]
no problem. many thanks!

**Comment by asmwarrior** [comment]
I just checked this issue today, I'm using the Firefox 103, and it looks like when I click the logout, I can correctly logout, but when I open the homepage: http://127.0.0.1:5000, I was still logged in, so is there any way to truly logout? Thanks.

My change of the project by adding the python 3 support is here:

https://github.com/asmwarrior/Simple-File-Server

**Comment by RDCH106** [comment]
> I just checked this issue today, I'm using the Firefox 103, and it looks like when I click the logout, I can correctly logout, but when I open the homepage: http://127.0.0.1:5000, I was still logged in, so is there any way to truly logout? Thanks.

The problem is only in Firefox and how it manages HTTP Basic Auth. Nothing to do at the moment 😅.
